## Using NumPy 

In [1]:
!pip install NumPy

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np

### Creating array

#### 1-Dimensional array

In [3]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
temperatures_w1

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

#### 2.	Inspection and Properties

In [5]:
temperatures_w1.shape

(7,)

In [6]:
temperatures_w1.dtype

dtype('float64')

In [7]:
temperatures_w1.size

7

#### 3.	Array Operations

In [8]:
temperatures_in_F = (temperatures_w1*9/5)+32
temperatures_in_F

array([72.5 , 77.54, 69.44, 74.12, 78.98, 76.64, 71.42])

In [16]:
print(f"Maximum temperatures of the week = {temperatures_w1.max()}")
print(f"Minimum temperatures of the week = {temperatures_w1.min()}")

Maximum temperatures of the week = 26.1
Minimum temperatures of the week = 20.8


In [20]:
f'Average tempratures of the week = {temperatures_w1.mean():.2f}'

'Average tempratures of the week = 23.54'

#### 4.	Array Slicing and Indexing

In [24]:
f"Temperatures for the first three days of the week = {temperatures_w1[:3]}"

'temperatures for the first three days of the week = [22.5 25.3 20.8]'

In [25]:
f"Temperatures for the weekend last two days = {temperatures_w1[-2:]}"

'Temperatures for the weekend last two days = [24.8 21.9]'

In [26]:
f"Temperatures for the middle three days of the week = {temperatures_w1[2:5]}"

'Temperatures for the middle three days of the week = [20.8 23.4 26.1]'

#### 5.	Create a 2D Array

In [33]:
temperatures = np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
                [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] 
               ])
temperatures

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

In [34]:
print(temperatures.shape)
print(temperatures.dtype)
temperatures .size

(2, 7)
float64


14

In [35]:
f"The temperatures for the first week = {temperatures[:1]}"

'The temperatures for the first week = [[22.5 25.3 20.8 23.4 26.1 24.8 21.9]]'

In [37]:
f"The temperatures for the second week = {temperatures[1:2]}"

'The temperatures for the second week = [[19.2 22.5 21.3 24.  23.5 22.8 20.1]]'

In [39]:
print(F"The temperatures for the first three days of each week = {temperatures[:,:3]}")

The temperatures for the first three days of each week = [[22.5 25.3 20.8]
 [19.2 22.5 21.3]]


In [42]:
F"The temperatures for the weekends (last two days) of both weeks = {temperatures[:,-2:]}"

'The temperatures for the weekends (last two days) of both weeks = [[24.8 21.9]\n [22.8 20.1]]'